# For more ideas, see https://github.com/actions/labeler#common-examples

system:
  - .github/**/*

l10n-de:
  - files/de/**/*

l10n-es:
  - files/es/**/*

l10n-fr:
  - files/fr/**/*

l10n-ja:
  - files/ja/**/*

l10n-ko:
  - files/ko/**/*
  - docs/ko/**/*

l10n-pl:
  - files/pl/**/*

l10n-pt-br:
  - files/pt-br/**/*

l10n-ru:
  - files/ru/**/*
  - docs/ru/**/*

l10n-zh:
  - files/zh-cn/**/*
  - files/zh-tw/**/*
  - docs/zh-cn/**/*
  - docs/zh-tw/**/*
